name       : openjdk-11
version    : 11.0.11
release    : 9
source     :
    - https://hg.openjdk.java.net/jdk-updates/jdk11u/archive/jdk-11.0.11-ga.tar.bz2 : ddf99ff3eed932a2aa6b0db686fdee86dcb0c29cbc783051757a1cfbc920a8f2
    - https://hg.openjdk.java.net/openjfx/11-dev/rt/archive/11.0.11+1.tar.bz2 : 6cd9d644d5c604320204915e30d1e30055011596f88f6eb0a62e7983c8a7a2f1
license    : GPL-2.0-with-classpath-exception
component  : programming.java
homepage   : https://openjdk.java.net/
summary    : Open implementation of Oracle's Java Development Kit version 11
description: |
    Open implementation of Oracle's Java Development Kit, major version 11. This package includes both the JDK and its accompanying JRE, along with OpenJFX 11.
ccache     : no
networking : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libjpeg)
    - pkgconfig(x11)
    - pkgconfig(xext)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xt)
    - pkgconfig(xtst)
    - pkgconfig(xxf86vm)
    - apache-ant
    - cups-devel
    - giflib-devel
    - openjdk-11-devel
    - p7zip
setup      : |
    # Build OpenJFX
    mkdir openjfx-11
    tar xf $sources/11.*.tar.bz2 -C $workdir/openjfx-11/ --strip-components=1
    pushd openjfx-11/

    export JAVA_HOME=/usr/lib64/openjdk-11
    export GRADLE_USER_HOME=$workdir/.gradle_home
    export TERM=xterm

    bash gradlew zips \
        --no-daemon \
        --stacktrace \
        -PCONF=DebugNative

    popd
    # done with OpenJFX

    %patch -p1 < $pkgfiles/0001-Double-default-reserved-code-cache-size.patch
    %patch -p1 < $pkgfiles/0001-Enable-tiered-compilation.patch

    chmod +x configure
    %configure --prefix="$installdir/usr" \
        --with-jvm-variants=client \
        --with-jvm-features="compiler2" \
        --with-boot-jdk="/usr/lib64/openjdk-11" \
        --with-native-debug-symbols=internal \
        --with-version-pre="" \
        --with-version-opt="solus" \
        --with-stdc++lib=dynamic \
        --with-freetype=system \
        --with-giflib=system \
        --with-harfbuzz=system \
        --with-lcms=system \
        --with-libjpeg=system \
        --with-libpng=system \
        --with-zlib=system \
        --enable-unlimited-crypto \
        --disable-warnings-as-errors \
        --disable-absolute-paths-in-output \
        --with-extra-cflags="$CFLAGS" \
        --with-extra-cxxflags="$CXXFLAGS" \
        --with-extra-ldflags="$LDFLAGS" \
        --with-import-modules=$workdir/openjfx-11/build/modular-sdk \
        --with-cacerts-file=%libdir%/openjdk-11/lib/security/cacerts \
        --with-jobs=%YJOBS%
build      : |
    # Build OpenJDK and JRE
    make images legacy-jre-image
install    : |
    install -Ddm 00755 $installdir/%libdir%/ 
    mkdir -p $installdir/usr/include/openjdk-11/ $installdir/usr/share/applications/

    make install

    # Binaries
    mv $installdir/usr/jvm/openjdk-* $installdir/%libdir%/openjdk-11/
    rm -rf $installdir/usr/jvm/
    rm -rf $installdir/usr/bin/

    # Remove license files and demo files
    rm -rf $installdir/%libdir%/openjdk-11/{legal,demo}/

    # Headers
    cd build/linux-x86_64-*/
    cp -ar jdk/include/* $installdir/usr/include/openjdk-11/
    # Symlink header files (because some apps look for them in $JAVA_HOME)
    ln -s /usr/include/openjdk-11/ $installdir/%libdir%/openjdk-11/include/

    # Man pages
    mv $installdir/%libdir%/openjdk-11/man/ $installdir/usr/share/
    find $installdir/usr/share/man/ -type f -exec rename -- ".1" "-11.1" {} \;
    # Remove pre-existing symlink first
    rm $installdir/usr/share/man/ja
    mv -f $installdir/usr/share/man/ja_JP.UTF-8/ $installdir/usr/share/man/ja/

    # Add java-11-jar.desktop into usable apps
    install -Dm 00644 $pkgfiles/java-11-jar.desktop $installdir/usr/share/applications/
