name       : openjdk-11
version    : 11.0.8
release    : 1
source     :
    - http://hg.openjdk.java.net/jdk-updates/jdk11u/archive/jdk-11.0.8+5.tar.bz2 : 56fe2712180b6efe81bb0b9b1bbaf8abb27fc9b03213fefb91194e51a44b559f
    - https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz : 99be79935354f5c0df1ad293620ea36d13f48ec3ea870c838f20c504c9668b57
license    : GPL-2.0-with-classpath-exception
component  : programming.java
summary    : Open implementation of Oracle's Java Development Kit
description: |
    Open implementation of Oracle's Java Development Kit
ccache     : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(lcms2)
    - pkgconfig(libjpeg)
    - pkgconfig(x11)
    - pkgconfig(xext)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xt)
    - pkgconfig(xtst)
    - cups-devel
    - giflib-devel
    - p7zip
setup      : |
    # Unpack prebuilt tarball for bootstrap
    tar xvzf $sources/openjdk-11.0.2_linux-x64_bin.tar.gz -C $workdir

    bash ./configure --prefix="$installdir/usr" \
        --with-boot-jdk=$workdir/jdk-11.0.2 \
        --with-version-build=10 \
        --with-version-pre="" \
        --with-version-opt="" \
        --with-stdc++lib=dynamic \
        --with-giflib=system \
        --with-lcms=system \
        --with-libjpeg=system \
        --with-libpng=system \
        --with-zlib=system \
        --enable-unlimited-crypto \
        --disable-warnings-as-errors \
        --with-jobs=%YJOBS% \
        --with-extra-ldflags="$LDFLAGS"
build      : |
    make images
install    : |
    install -Ddm 00755 $installdir/%libdir% $installdir/usr/include/openjdk-11 $installdir/usr/share/man/man1
    make install

    # Binaries
    mv $installdir/usr/jvm/openjdk-%version% $installdir/%libdir%/openjdk-11
    rm -rf $installdir/usr/jvm
    rm -rf $installdir/usr/bin

    # Headers and man pages
    cd build/linux-x86_64-normal-server-release
    cp -ar jdk/include/* $installdir/usr/include/openjdk-11/.
    mv $installdir/usr/lib64/openjdk-11/man/man1/*.1 $installdir/usr/share/man/man1/

    # Add java-11-jar.desktop into usable apps
    install -Dm 00644 $pkgfiles/java-11-jar.desktop $installdir/usr/share/applications/java-11-jar.desktop
