name       : openjdk-11
version    : 11.0.8
release    : 3
source     :
    - https://hg.openjdk.java.net/jdk-updates/jdk11u/archive/jdk-11.0.8-ga.tar.bz2 : 0c10838f708a5987d2980aee56c5c50c02637e21387215f3e13358b93d107192
    - https://hg.openjdk.java.net/openjfx/11-dev/rt/archive/11.0.8+2.tar.bz2 : 64c1c4bf0639555592dcc38f34e231a4f245e79b17f995766161bd39957784ea
license    : GPL-2.0-with-classpath-exception
component  : programming.java
summary    : Open implementation of Oracle's Java Development Kit version 11
description: |
    Open implementation of Oracle's Java Development Kit, major version 11. This package includes both the JDK and its accompanying JRE, along with OpenJFX 11.
ccache     : no
networking : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libjpeg)
    - pkgconfig(x11)
    - pkgconfig(xext)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xt)
    - pkgconfig(xtst)
    - pkgconfig(xxf86vm)
    - apache-ant
    - cups-devel
    - giflib-devel
    - openjdk-11-devel
    - p7zip
setup      : |
    # Unpack openjfx for integration
    mkdir openjfx-11
    tar xjf $sources/11.*.tar.bz2 -C $workdir/openjfx-11/ --strip-components=1

    # Build OpenJFX
    pushd openjfx-11/
    %patch -p1 < $pkgfiles/disable-warnings-as-errors.patch
    chmod +x gradlew
    export CFLAGS="-Wno-error"
    JAVA_HOME=/usr/lib64/openjdk-11 GRADLE_USER_HOME=$workdir/.gradle ./gradlew zips --no-daemon
    popd

    chmod +x configure
    %configure --prefix="$installdir/usr" \
        --with-boot-jdk="/usr/lib64/openjdk-11" \
        --with-version-pre="" \
        --with-version-opt="solus" \
        --with-stdc++lib=dynamic \
        --with-giflib=system \
        --with-lcms=system \
        --with-libjpeg=system \
        --with-libpng=system \
        --with-zlib=system \
        --enable-unlimited-crypto \
        --disable-warnings-as-errors \
        --with-import-modules=$workdir/openjfx-11/build/modular-sdk \
        --with-cacerts-file=%libdir%/openjdk-11/lib/security/cacerts \
        --with-jobs=%YJOBS%
build      : |
    make images legacy-jre-image
install    : |
    install -Ddm 00755 $installdir/%libdir%/ 
    mkdir -p $installdir/usr/include/openjdk-11/ $installdir/usr/share/applications/

    make install

    # Binaries
    mv $installdir/usr/jvm/openjdk-* $installdir/%libdir%/openjdk-11/
    rm -rf $installdir/usr/jvm/
    rm -rf $installdir/usr/bin/

    # Remove license files
    rm -rf $installdir/usr/lib64/openjdk-11/legal/

    # Headers
    cd build/linux-x86_64-normal-server-release/
    cp -ar jdk/include/* $installdir/usr/include/openjdk-11/
    # Symlink header files (because some apps look for them in $JAVA_HOME)
    ln -s /usr/include/openjdk-11/ $installdir/usr/lib64/openjdk-11/include/

    # Man pages
    mv $installdir/usr/lib64/openjdk-11/man/ $installdir/usr/share/
    find $installdir/usr/share/man/ -type f -exec rename -- ".1" "-11.1" {} \;
    # Remove pre-existing symlink first
    rm $installdir/usr/share/man/ja
    mv -f $installdir/usr/share/man/ja_JP.UTF-8/ $installdir/usr/share/man/ja/

    # Add java-11-jar.desktop into usable apps
    install -Dm 00644 $pkgfiles/java-11-jar.desktop $installdir/usr/share/applications/
